const data = [
  {
    id: "1",
    product_img: "./img/perfume1.jpg",
    alt: "perfume",
    desc: "Aqua Di Gio POUR HOMME Perfume",
    price: 12000,
    addedToCart: false,
  },
  {
    id: "2",
    product_img: "./img/perfume2.jpg",
    alt: "perfume",
    desc: "Versace EROS perfume",
    price: 6700,
    addedToCart: false,
  },
  {
    id: "3",
    product_img: "./img/glass1.jpg",
    alt: "Glass",
    desc: "Glasses",
    price: 1200,
    addedToCart: false,
  },
  {
    id: "4",
    product_img: "./img/bracelet.jpg",
    alt: "Bracelet",
    desc: "Brcelet",
    price: 340,
    addedToCart: false,
  },
  {
    id: "5",
    product_img: "./img/shoes1.jpg",
    alt: "Shoes",
    desc: "Brown Sneakers",
    price: 3200,
    addedToCart: false,
  },
  {
    id: "6",
    product_img: "./img/knife.jpg",
    alt: "knife",
    desc: "Combat Knife",
    price: 890,
    addedToCart: false,
  },
  {
    id: "7",
    product_img: "./img/glass2.jpg",
    alt: "glasses",
    desc: "glasses",
    price: 2200,
    addedToCart: false,
  },
  {
    id: "8",
    product_img: "./img/shoes3.jpg",
    alt: "Shoes",
    desc: "Formal Shoes",
    price: 2300,
    addedToCart: false,
  },
  {
    id: "9",
    product_img: "./img/shoes2.jpg",
    alt: "Shoes",
    desc: "Chelsea Boots",
    price: 4800,
    addedToCart: false,
  },
  {
    id: "10",
    product_img: "./img/glass5.jpg",
    alt: "Glasses",
    desc: "Sunglasses",
    price: 3200,
    addedToCart: false,
  },
  {
    id: "11",
    product_img: "./img/watch1.jpg",
    alt: "Watch",
    desc: "Analog Watch",
    price: 7000,
    addedToCart: false,
  },
  {
    id: "12",
    product_img: "./img/perfume3.jpg",
    alt: "perfume",
    desc: "Diesel Fuel For Life Perfume",
    price: 3600,
    addedToCart: false,
  },
  {
    id: "13",
    product_img: "./img/bracelet1.jpg",
    alt: "Bracelet",
    desc: "Bracelet",
    price: 400,
    addedToCart: false,
  },
  {
    id: "14",
    product_img: "./img/watch2.jpg",
    alt: "Watch",
    desc: "Analog Watch",
    price: 9000,
    addedToCart: false,
  },
];
export default data;
